### ISSUE TITLE
Add design module flowchart

### ISSUE THREAD

**Issue by winstonwzhang** [SpicyChicken6/metabolomics_analysis_tools#8]
**Provide feedback on the logical deduction and level of detail available in the design documents, keeping in mind the practical applicability of the tool that you are evaluating.**

I would suggest you add a flowchart (created in either draw.io or powerpoint) that outlines the different modules present within your project. This would help visualize what your project is doing to the input .csv data.

For example, from the input data your project later applies normalization, PCA, and other analysis to the input. Does this happen in a serial fashion or a parallel (independent) fashion?

**Comment by SpicyChicken6** [comment]
Hello, thank you for your useful suggestions. I would like to add a flow chart for my modules. The downstream analysis after PCA could be performed in parallel.
